name = "my-static-website" # Replace with your desired project name (must be unique in your CF account)
compatibility_date = "2025-06-10" # You can use the date from your log or a more recent one like "2024-03-01"

# This [assets] section tells Wrangler to deploy the contents of the 'public' directory
# as static assets. Wrangler will automatically create a simple Worker to serve them.
[assets]
directory = "public"
# Optional: You can specify specific files/patterns to include or exclude if needed
# include = ["**/*.html", "**/*.css", "**/*.js"]
# exclude = ["**/ignored-file.txt"]