name = "uigenoutput" # Replace "my-static-site" with your desired project name
compatibility_date = "2025-06-10" # You can use the date from your log or a more recent one

# This section tells Wrangler to treat your project as a static site
# and specifies where the static files are located.
[site]
bucket = "." # "." means the current directory (root of your project)